apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
  labels:
    app: my-nginx
spec:
  type: {{ .Values.service.type }}
  selector:
    app: my-nginx
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      name: http
